global:
  scrape_interval: 5s #scrape metrics from targets every 5 seconds

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets:
    - localhost:9090  #scrape Prometheus on http://localhost:9090/metrics
- job_name: "HLDEBVM01"
  static_configs:
  - targets:
    - 192.168.68.240:9100

#alertmanager
rule_files:
  - /etc/prometheus/alerts.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'